name: RealTXN.com
markdown: kramdown
permalink: /:year/:month/:title
future: false
sass:
  style: :compressed
nav_right:
- text: Sign Up
  url: /
  permalink: http://app.realtxn.com/users/sign_up
  desktop_only: true
- text: FAQs
  url: /
  permalink: /#!/faqs
  desktop_only: false
- text: What's New?
  url: /blog/index.html
  permalink: /blog
  desktop_only: true
- text: Sign In
  url: http://app.realtxn.com/users/sign_in
  permalink: http://app.realtxn.com/users/sign_in
  desktop_only: false
authors:
  rdr:
    name: Dallas Read
    position: Developer
    plus: +DallasRead
    initials: rdr
